list:
  response:
    type: object
    properties:
      id:
        type: integer
        description: Product ID
      name:
        type: string
        description: Product name
      code:
        type: string
        description: Product code
      price:
        type: number
        description: Product price
      quantity:
        type: integer
        description: Product quantity
      description:
        type: string
        description: Product description

create:
  request:
    type: object
    properties:
      name:
        type: string
        description: Product name
      code:
        type: string
        description: Product code
      price:
        type: number
        description: Product price
      quantity:
        type: integer
        description: Product quantity
      description:
        type: string
        description: Product description
  response:
    type: object
    properties:
      id:
        type: integer
        description: Product ID
      name:
        type: string
        description: Product name
      code:
        type: string
        description: Product code
      price:
        type: number
        description: Product price
      quantity:
        type: integer
        description: Product quantity
      description:
        type: string
        description: Product description

getById:
  response:
    type: object
    properties:
      id:
        type: integer
        description: Product ID
      name:
        type: string
        description: Product name
      code:
        type: string
        description: Product code
      price:
        type: number
        description: Product price
      quantity:
        type: integer
        description: Product quantity
      description:
        type: string
        description: Product description

update:
  request:
    type: object
    properties:
      name:
        type: string
        description: Product name
      code:
        type: string
        description: Product code
      price:
        type: number
        description: Product price
      quantity:
        type: integer
        description: Product quantity
      description:
        type: string
        description: Product description
